mrozycki/rustmas

- Cargo.lock
- configurator/Cargo.toml
- configurator/src/capture.rs
- configurator/src/main.rs
> Implement 3D points mapping from perspectives

- .gitignore
- Cargo.lock
- configurator/Cargo.toml
- configurator/src/capture.rs
- configurator/src/cv.rs
- configurator/src/main.rs
> Add saving led position images

- animator/src/animations/rainbow_cylinder.rs
- animator/src/animations/rainbow_sphere.rs
- animator/src/animations/rainbow_waterfall.rs
- animator/src/animations/rgb.rs
- animator/src/animations/sweep.rs
- animator/src/controller.rs
- animator/src/main.rs
Co-authored-by: pnwkw <pnwkw@users.noreply.github.com>
> Allow run-time control of the animator

- light-client/src/lib.rs
> Change the post data format to align with the pico w server

- animator/src/lib.rs
- light-client/src/lib.rs
> Add retry when light connection fails

- Cargo.lock
- webapi/src/main.rs
- webui/Cargo.toml
- webui/src/main.rs
> Load animation list from backend

- .github/workflows/rust.yml
- animator/Cargo.toml
- animator/src/cli.rs
- animator/src/lib.rs
- configurator/Cargo.toml
- configurator/src/main.rs
- light-client/Cargo.toml
- light-client/src/lib.rs
- webapi/Cargo.toml
> Add feature gate for OpenGL visualiser

- Cargo.lock
- Cargo.toml
- animation-model/Cargo.toml
- animation-model/src/lib.rs
- animation-model/src/parameter_schema.rs
- animator/Cargo.toml
- animator/src/animations/animation.rs
- animator/src/animations/barber_pole.rs
- animator/src/animations/rainbow_sphere.rs
- animator/src/animations/rainbow_waterfall.rs
- animator/src/animations/random_sweep.rs
- animator/src/animations/sweep.rs
- animator/src/lib.rs
It was not placed inside animator crate, since it will be used by webui, which requires code to be compilable to wasm, and some of the things in animator are not. Therefore a separate crate was created, which will be entirely compilable to wasm, and therefore usable within webui.
> Create animation parameter schema

- webui/src/controls/color_control.rs
- webui/src/controls/mod.rs
Co-authored-by: pnwkw <pnwkw@users.noreply.github.com>
closes #58
> webui: Add warm white colors to color picker

- .env.example
- .gitignore
- Cargo.lock
- webapi/Cargo.toml
- webapi/Migrant.toml
- webapi/migrations/20221121214212_initial-db/down.sql
- webapi/migrations/20221121214212_initial-db/up.sql
- webapi/src/db.rs
- webapi/src/main.rs
> webapi: Save set parameters in database

- Cargo.lock
- webapi/src/main.rs
- webui/Cargo.toml
- webui/src/api.rs
- webui/src/controls/debouncer.rs
- webui/src/controls/mod.rs
Co-authored-by: pnwkw <pnwkw@users.noreply.github.com>
> webui: Update parameters on form change

- Cargo.lock
- animator/Cargo.toml
- animator/src/animations/animation.rs
- animator/src/animations/barber_pole.rs
- animator/src/animations/blank.rs
- animator/src/animations/brightness_controlled.rs
- animator/src/animations/check.rs
- animator/src/animations/mod.rs
- animator/src/animations/rainbow_cable.rs
- animator/src/animations/rainbow_cylinder.rs
- animator/src/animations/rainbow_sphere.rs
- animator/src/animations/rainbow_spiral.rs
- animator/src/animations/rainbow_waterfall.rs
- animator/src/animations/random_sweep.rs
- animator/src/animations/rgb.rs
- animator/src/animations/speed_controlled.rs
- animator/src/animations/sweep.rs
- animator/src/lib.rs
This allows for a StepAnimation, which is updated with a time delta, and then rendered, rather than just being rendered with absolute time value.
> animator: Refactor Animation trait

- configurator/src/capture.rs
> Omit writing headers to csv files

- Cargo.lock
- configurator/Cargo.toml
- configurator/src/capture.rs
> configurator: Remove outliers by distance in 2D

- webui/src/controls/mod.rs
- webui/src/main.rs
> webui: Confirm before switching with unsaved changes

- animator/src/animations/barber_pole.rs
- animator/src/animations/direction_controlled.rs
- animator/src/animations/mod.rs
- animator/src/animations/rainbow_cable.rs
- animator/src/animations/rainbow_cylinder.rs
- animator/src/animations/rainbow_sphere.rs
- animator/src/animations/rainbow_spiral.rs
- animator/src/animations/rainbow_waterfall.rs
> Add time-reversible decorator

- animator/src/animations/animation.rs
- animator/src/animations/barber_pole.rs
- animator/src/animations/blank.rs
- animator/src/animations/brightness_controlled.rs
- animator/src/animations/check.rs
- animator/src/animations/detection_status.rs
- animator/src/animations/direction_controlled.rs
- animator/src/animations/indexing.rs
- animator/src/animations/manual_sweep.rs
- animator/src/animations/mod.rs
- animator/src/animations/rainbow_cable.rs
- animator/src/animations/rainbow_cylinder.rs
- animator/src/animations/rainbow_sphere.rs
- animator/src/animations/rainbow_spiral.rs
- animator/src/animations/rainbow_waterfall.rs
- animator/src/animations/random_sweep.rs
- animator/src/animations/rgb.rs
- animator/src/animations/speed_controlled.rs
- animator/src/animations/sweep.rs
- animator/src/lib.rs
- webapi/src/main.rs
- webui/src/api.rs
- webui/src/controls/mod.rs
- webui/src/main.rs
- webui/style.css
> webui: Add animation name headers

- configurator/src/capture.rs
- configurator/src/main.rs
> Implement removing outliers by 3d distance

- configurator/src/capture.rs
- configurator/src/main.rs
> Implement extrapolating missing lights at the end of the string

- configurator/src/main.rs
> Implement 2D configurator

- visualizer/src/lib.rs
- visualizer/src/pan_orbit_camera.rs
- visualizer/src/websocket.rs
> visualizer: Add visual improvements

- configurator/README.md
- configurator/src/capture.rs
- configurator/src/cv.rs
> Add preview to configurator

- events/src/fft_generator.rs
> events: Add support for i8, i16 and i32 sample formats

- animator/src/factory.rs
Added a warning log in animator if any detected plugins are not executable. These plugins will also not show up in the webui. This should make it easier to notice that animations were not built.
Inspired by https://github.com/krzmaz/pico-w-neopixel-server/discussions/9#discussioncomment-7917741
cc @2m
> animator: Detect non-executable plugins

- animations/src/bin/random_sweep.rs
* fix zero-length frames being sent after every sweep
* add lead length for smoother look
> Fix minor issues in Random Sweep animation
